### ISSUE TITLE
Co sądzimy o The Unicorn Project

### ISSUE THREAD

**Issue by kaluzaaa** [patoarchitekci/uservoice#1]
Od @ziembor:
czytałeś pewnie Project Phoenix - tak strasznie reklamowany np. przez Darka Porowskiego (cyz generalnie ludzi z polskiego MS) jako świetny opis praktyk devopsowych itp. Szczerze pisząc, ja tam znajdowałem porządnie zorkiestrowaną organizację ITL-ową (pewnie pomieszało im się z następną książką Gene Kima). Na DevOps itp. przyszedł czas teraz. Wyszedł The Unicorn Project: A Novel about Developers, Digital Disruption, and Thriving in the Age of Data.
Udało Ci się na niego zerknąć? Ciekaw byłbym waszej dyskusji o tym na Pato. 🙂

**Comment by bkielbasa** [comment]
Już powoli kończę książkę i powiem tak - dla mnie fajnie się to czyta (słucha) z tego względu, że widzę problemy, które miałem kiedyś (no dobrze, nie aż tak wielkie jak oni!).

Ciekawe jest poczytać jak dochodzą do praktyk, które teraz próbuje się wpychać agile itp ale tak z punktu widzenia bardziej biznesu.

**Comment by kaluzaaa** [comment]
Hej @ziembor!

Dzięki za to pytanie. Poruszyliśmy je w [odcinku #35](https://patoarchitekci.io/35/).
Jeśli uważasz, że trzeba wejść głębiej w temat to zapraszamy do otwarcia, dodania pytania i dyskusji tutaj 😁
