### ISSUE TITLE
Azure Service Fabric w 2020?

### ISSUE THREAD

**Issue by devmonte** [patoarchitekci/uservoice#16]
Czy jest sens brać do nowych projektów? SF vs K8s? Znane wdrożenia? Czy warto się tej technologii uczyć? Inne przemyślenia i znane z doświadczenia historie?

**Comment by kaluzaaa** [comment]
Cześć,

Dzięki za to pytanie. Poruszyliśmy je w [odcinku #35](https://patoarchitekci.io/35/).
Jeśli uważasz, że trzeba wejść głębiej w temat to zapraszamy do otwarcia, dodania pytania i dyskusji tutaj 😁
