### ISSUE TITLE
Data warehousing, data lakes

### ISSUE THREAD

**Issue by lkurzyniec** [patoarchitekci/uservoice#17]

**Comment by maklipsa** [comment]
Ho ho ho. 
Żyjemy i do tematu wracamy i to z gościem. Będzie! :)

**Comment by kaluzaaa** [comment]
@lkurzyniec no to zostałeś naszą muzą i powstał odcinek #36 - https://patoarchitekci.io/36/

**Comment by lkurzyniec** [comment]
Cieszy mnie to niezmiernie :-)
