### ISSUE TITLE
#patopytanie - patologiczne mikroserwisy

### ISSUE THREAD

**Issue by kaluzaaa** [patoarchitekci/uservoice#18]
#patopytanie co was wkurza w mikro serwisach? w czym was pokonały? o czym ludzie nie mówią?

---
Stare: Jak duży patologiczny overhead wprowadzają mikroserwisy

**Comment by mgrabarz** [comment]
Ciekawe jak się do tego mają SOLIDnie napisane nanoserwisy i pikoserwisy?

**Comment by rafalpienkowski** [comment]
Kiedyś to komunikacja między modułami aplikacji była prosta. Wywoływało się metodę z innego modułu i czekało na odpowiedź. A teraz asynchroniczna komunikacja, circuit breaker, retry policy, idempotentne wiadomości a na koniec dnia i tak trzeba wdrożyć wszystkie usługi jednocześnie, bo inaczej aplikacja wybuchnie...

**Comment by bkielbasa** [comment]
czym tak naprawdę mikrosierwisy są? Czy rzeczywiście chodzi o to by można było to przepisać w 2 tygodnie?

No i należy wspomnieć o tym o ile więcej problemów będziemy mięli z nimi - opóźnienia/rozproszone transakcje (kochamy transakcje, prawdaż?), (a)synchroniczność/ monitorowanie (tracing/logi).

Mi osobiście spodobało się stwierdzenie - jeśli nie potrafisz zrobić dobrego modularnego monolitu, to nie pchaj się w mikroserwisy, bo tego tym bardziej nie będziesz umiał :P

**Comment by kaluzaaa** [comment]
@bkielbasa odrazu modularnego ;-) Ja stawiam poprzeczkę trochę niżej już na skalowalnym monolicie ;-)

**Comment by krzysztofhalasa** [comment]
Mikroserwis mikroserwisem, ale finalnie i tak ciężko unikać pre-definiowanych modeli danych latających po kolejce. Sprzężenia są, tylko trudniejsze do wykrycia niż w klasycznym API-w-API. To jest jak z alkoholem - nie próbować, jak się nie jest dojrzałym

**Comment by kaluzaaa** [comment]
#patopytanie co was wkurza w mikro serwisach? w czym was pokonały? o czym ludzie nie mówią?

**Comment by rmaziarka** [comment]
To ja połączę 2 pytania w "Co was wkurza, że ludzie nie mówią" 😉
- brak rozróżnienia na dane prywatne i publiczne / zewnętrzne (np. jak zareaguje nasz ms B na zmiany, jeśli zmieni się model współpracy z ms A od którego bierzemy dane)
- brak przemyślanej komunikacji na poziomie technicznym (np. jeśli mamy w ms A 1mln rekordów to jak wysyłać tylko zmiany różnicowe do ms B i jak być pewnym, że ms B te zmiany odebrał)
- brak przemyślonej komunikacji na poziomie biznesowym (np. co się stanie jeśli ms A wyśle żądanie do ms B, a on to zapytanie odrzuci z powodu walidacji)
- brak myślenia o race-conditionach na poziomie komunikacji mikroserwisowej (np. co jeśli w ms A były akcje 1,2,3, ale do ms B dojdą one 2,3,1)
To tak na szybko, po ostatnim warsztacie ES 😀

**Comment by kaluzaaa** [comment]
Dzięki wszystkim za udzielanie się! :-)

Wykorzystaliśmy wasze opinie w [odcinku #33](https://patoarchitekci.io/33/)
