### ISSUE TITLE
Gateway Aggregation

### ISSUE THREAD

**Issue by lkurzyniec** [patoarchitekci/uservoice#3]
Świetnie poprowadzony odcinek o Circuit breaker. Poproszę to samo na temat Gateway Aggregation.

**Comment by kaluzaaa** [comment]
Pierwszy z dwóch odcinków już jest https://patoarchitekci.io/18/

**Comment by lkurzyniec** [comment]
Pięknie! 💪

**Comment by kaluzaaa** [comment]
No i jest Gateway Aggregation - https://patoarchitekci.io/19/

**Comment by lkurzyniec** [comment]
Świetnie 🤜🤛
