### ISSUE TITLE
Transakcyjnosc w systemach rozproszonych

### ISSUE THREAD

**Issue by witek1902** [patoarchitekci/uservoice#5]
Jak podejść do "transakcyjnych operacji biznesowych"  w systemach rozproszonych?
Jakie są na to patterny? Jakie są Wasze doświadczenia z poszczególnymi podejsciami?

**Comment by s-kramer** [comment]
plus jak zrobić dobry sharing, jak dobrze zamodelować dane żeby tych transakcji unikać - @kaluzaaa wspominał o tym w pierwszych odcinkach kilka razy z tego co pamiętam, fajnie by było pociągnąć temat
I'd pay for that.

**Comment by kaluzaaa** [comment]
@witek1902 @s-kramer

Dzięki za to pytanie. Poruszyliśmy je w [odcinku #35](https://patoarchitekci.io/35/).

Jeśli uważacie, że trzeba wejść głębiej w temat to zapraszamy do otwarcia lub nowego issues, dodania pytania i dyskusji tutaj 😁
