### ISSUE TITLE
Nowe wersje starych szyn danych - czy to ma sens?

### ISSUE THREAD

**Issue by witek1902** [patoarchitekci/uservoice#6]
Czy Waszym zdaniem w aktualnym świecie jest jeszcze miejsce na takie rozwiązania jak MuleESB?
Czy gdziekolwiek warto tego używać?
Jeśli tak, dlaczego?
Jesli nie, dlaczego?

**Comment by kaluzaaa** [comment]
Cześć,

Dzięki za to pytanie. Poruszyliśmy je w [odcinku #35](https://patoarchitekci.io/35/).
Jeśli uważasz, że trzeba wejść głębiej w temat to zapraszamy do otwarcia, dodania pytania i dyskusji tutaj 😁
