### ISSUE TITLE
Serverless 

### ISSUE THREAD

**Issue by PawelHaracz** [patoarchitekci/uservoice#8]
Co sądzicie o przyszłości serverlessa, jak on się może rozwijać. Czy tworzenie dużych systemów opartych o event-driven i serverless to dobry pomysł. czyli po prostu Wasza opinia o przyszłości serverlessa

**Comment by kaluzaaa** [comment]
@PawelHaracz słuchałeś https://patoarchitekci.io/10/ oraz https://patoarchitekci.io/2/?

**Comment by PawelHaracz** [comment]
Close. Zapomniałem o drugim odcinku
